version: 2
updates:
- package-ecosystem: cargo
  directory: "/."
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: isahc
    versions:
    - 1.0.3
    - 1.1.0
    - 1.2.0
    - 1.3.0
  - dependency-name: syn
    versions:
    - 1.0.60
    - 1.0.61
    - 1.0.62
    - 1.0.63
    - 1.0.64
    - 1.0.65
    - 1.0.66
  - dependency-name: serde
    versions:
    - 1.0.119
    - 1.0.124
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: svg
    versions:
    - 0.9.0
  - dependency-name: lyon
    versions:
    - 0.17.4
  - dependency-name: bytemuck
    versions:
    - 1.5.0
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.0
    - 5.21.1
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.1
    - 5.26.2
    - 5.26.3
    - 5.27.0
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.4.0
    - 31.5.0
    - 31.6.0
    - 31.6.1
    - 32.0.0
    - 32.0.1
    - 32.0.2
    - 32.0.3
    - 32.1.0
    - 32.1.1
    - 32.2.0
    - 32.3.0
    - 32.3.1
    - 32.3.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@wdio/cli"
    versions:
    - 6.12.1
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.7
