[workspace]
members = [
    "core",
    "core/macros",
    "desktop",
    "scanner",
    "swf",
    "web",
]

# Don't optimize build scripts and macros.
[profile.release.build-override]
opt-level = 0
